# Generated by Django 5.1.1 on 2024-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='periode',
            field=models.IntegerField(choices=[(0, 'Aucun periode'), (1, 'Mensuel'), (2, 'Trimestriel'), (3, 'Semestreil'), (4, 'Annuel')], default=0),
        ),
    ]
