# Generated by Django 5.1.1 on 2024-11-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0001_initial'),
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='montant',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Detail_contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.cotisation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membre.membre')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='DetailCotisation',
        ),
    ]
