# Generated by Django 5.1.1 on 2024-11-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0002_contribution_montant_detail_contribution_and_more'),
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail_contribution',
            new_name='DetailContribution',
        ),
    ]
