# Generated by Django 5.1.1 on 2024-10-10 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0002_alter_cotisation_periode'),
        ('type_cotisation', '0005_alter_type_cotisation_montant_max_retrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='type_cotisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_cotisation', to='type_cotisation.type_cotisation'),
            preserve_default=False,
        ),
    ]
