# Generated by Django 5.1.1 on 2024-10-10 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0003_cotisation_type_cotisation'),
        ('type_cotisation', '0006_alter_type_cotisation_montant_max_retrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='type_cotisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisation_type_cotisation', to='type_cotisation.type_cotisation'),
        ),
    ]
