# Generated by Django 5.1.1 on 2024-10-09 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField(null=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_valide', models.DateTimeField(blank=True, null=True)),
                ('user_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_cotisation_create', to=settings.AUTH_USER_MODEL)),
                ('user_delete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_cotisation_delete', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_cotisation_update', to=settings.AUTH_USER_MODEL)),
                ('user_valide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_cotisation_valide', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'type_cotisation_type',
                'ordering': ('-id',),
            },
        ),
    ]
