# Generated by Django 5.1.1 on 2024-10-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_cotisation', '0002_type_cotisation_montant_max_retrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_cotisation',
            name='montant_max_retrait',
            field=models.FloatField(default=None, null=True),
        ),
    ]
