# Generated by Django 5.1.1 on 2024-10-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_cotisation', '0006_alter_type_cotisation_montant_max_retrait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_cotisation',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='type_cotisation',
            name='date_delete',
        ),
        migrations.RemoveField(
            model_name='type_cotisation',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='type_cotisation',
            name='date_valide',
        ),
        migrations.RemoveField(
            model_name='type_cotisation',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='type_cotisation',
            name='user_delete',
        ),
        migrations.RemoveField(
            model_name='type_cotisation',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='type_cotisation',
            name='user_valide',
        ),
    ]
