# Generated by Django 5.1.1 on 2024-10-11 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_cotisation', '0007_remove_type_cotisation_date_create_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='type_cotisation',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='type_cotisation',
            name='date_delete',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='type_cotisation',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='type_cotisation',
            name='date_validate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type_cotisation',
            name='user_create',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_cotisation_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='type_cotisation',
            name='user_delete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_cotisation_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='type_cotisation',
            name='user_valide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_cotisation_validated', to=settings.AUTH_USER_MODEL),
        ),
    ]
