# Generated by Django 5.1.1 on 2024-11-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('date_assistance', models.DateTimeField()),
                ('montant_assistance', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_validate', models.DateTimeField(blank=True, null=True)),
                ('date_delete', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'assistance_assistance',
                'ordering': ('-id',),
            },
        ),
    ]
