# Generated by Django 5.1.1 on 2024-10-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0003_alter_assistance_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='user_delete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='user_valide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_validated', to=settings.AUTH_USER_MODEL),
        ),
    ]
