# Generated by Django 3.2.16 on 2024-08-19 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='user_delete',
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_validate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='user_create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membre',
            name='user_valide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre_valide', to=settings.AUTH_USER_MODEL),
        ),
    ]
