# Generated by Django 5.1.1 on 2024-10-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0002_auto_20240819_1441'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membre',
            table='membre_membre',
        ),
    ]
