# Generated by Django 5.1.1 on 2024-10-11 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotisation', '0004_alter_cotisation_type_cotisation'),
        ('membre', '0003_alter_membre_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_validate', models.DateTimeField(blank=True, null=True)),
                ('date_delete', models.DateTimeField(null=True)),
                ('cotisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisation_detail_cotisation', to='cotisation.cotisation')),
                ('membre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre_detail_cotisation', to='membre.membre')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_created', to=settings.AUTH_USER_MODEL)),
                ('user_delete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_deleted', to=settings.AUTH_USER_MODEL)),
                ('user_valide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detail_cotisation_detail',
                'ordering': ('-id',),
            },
        ),
    ]
