# Generated by Django 5.1.1 on 2024-10-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_cotisation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail_cotisation',
            old_name='montant',
            new_name='montant_paye',
        ),
    ]
