# Generated by Django 5.1.1 on 2024-10-24 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_cotisation', '0002_rename_montant_detail_cotisation_montant_paye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_cotisation',
            name='user_delete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detail_cotisation',
            name='user_valide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_validated', to=settings.AUTH_USER_MODEL),
        ),
    ]
